### ISSUE TITLE
3.0.x roadmap

### ISSUE THREAD

**Issue by grzhan** [MoePlayer/hexo-tag-aplayer#27]
- [x] Object-oriented design
- [x] Support external `Aplayer.js` resource, see #24 
- [x] Support external lyric resource, see #23 
- [x] Support Meting API, see #21 
- [x] Fix duplicate `Aplayer.js` loading, see #22 
- [x] Configurable in `_config.yml`

**Comment by syhily** [comment]
Cool, let's make `hexo-tag-aplayer` great again.
